pcc: lower SSA phi nodes with parallel copies

diff --git a/src/dev/pcc/pcc-tests/regress/gcccompat/Makefile b/src/dev/pcc/pcc-tests/regress/gcccompat/Makefile
--- a/src/dev/pcc/pcc-tests/regress/gcccompat/Makefile
+++ b/src/dev/pcc/pcc-tests/regress/gcccompat/Makefile
@@ -13,6 +13,7 @@ REGRESS_TARGETS = attribute001 attribute002 \
 	extension006 extension007 extension008
 
 OPT_REGRESS_TARGETS = typeof001
+OPT_FALLBACK_TARGETS = extension004
 
 # These extensions are not currently supported.
 # Do not complain about them as failed.
@@ -29,6 +30,13 @@ test:
 			./$$TARGET.out >/dev/null && \
 			echo "passed" || echo "failed" ;\
 	done 
+	@for TARGET in ${OPT_FALLBACK_TARGETS} ;\
+	do \
+		printf  "   %-20s \t\t " "$$TARGET(O2 fallback)" ;\
+		${CC} ${CFLAGS} -O2 -o $$TARGET.opt.out $$TARGET.c 2>/dev/null 1>&2 && \
+			./$$TARGET.opt.out >/dev/null && \
+			echo "passed" || echo "failed" ;\
+	done
 	@for TARGET in ${OPT_REGRESS_TARGETS} ;\
 	do \
 		printf  "   %-20s \t\t " "$$TARGET" ;\
@@ -70,4 +78,3 @@ clean:
 	/bin/rm -rf *.out 
 	/bin/rm -rf *.core
 	/bin/rm -rf ${LOG}
-
diff --git a/src/dev/pcc/pcc-tests/regress/misc/Makefile b/src/dev/pcc/pcc-tests/regress/misc/Makefile
--- a/src/dev/pcc/pcc-tests/regress/misc/Makefile
+++ b/src/dev/pcc/pcc-tests/regress/misc/Makefile
@@ -12,6 +12,7 @@ MAKE=make
 REGRESS_TARGETS = arith001 arith002 stasg001 ucmp001 char001 func001 str001 ucn001 array001 ucharload001 nestedcall001 intfp001 llshift001
 OPTIM_TARGETS = optim001 optim002 optim003 spillcost001 spillfp001 spillabi001 \
 	spillremat001
+SSA_TARGETS = ssaphi001
 PIC_TARGETS = pic001
 
 REGRESS_TARGETS_FAIL = 
@@ -25,6 +26,13 @@ test:
 			./$$TARGET.out >/dev/null && \
 			echo "passed" || echo "failed" ;\
 	done 
+	@for TARGET in ${SSA_TARGETS} ;\
+	do \
+		printf  "   %-20s \t\t " "$$TARGET" ;\
+		${CC} -O -Wc,-xssa ${CFLAGS} -o $$TARGET.out $$TARGET.c 2>/dev/null && \
+			./$$TARGET.out >/dev/null && \
+			echo "passed" || echo "failed" ;\
+	done
 	@for TARGET in ${OPTIM_TARGETS} ;\
 	do \
 		printf  "   %-20s \t\t " "$$TARGET" ;\
